import jsPDF from "jspdf";
import type { Database } from "@/integrations/supabase/types";

type Scan = Database["public"]["Tables"]["scans"]["Row"];

async function imgToDataURL(url: string): Promise<string | null> {
  try {
    const r = await fetch(url);
    const b = await r.blob();
    return await new Promise((res) => {
      const fr = new FileReader();
      fr.onload = () => res(fr.result as string);
      fr.onerror = () => res(null);
      fr.readAsDataURL(b);
    });
  } catch { return null; }
}

export async function downloadScanReport(scan: Scan) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 48;

  doc.setFillColor(26, 60, 42);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("FruitSense AI · Analysis Report", 40, 50);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(new Date(scan.created_at).toLocaleString(), 40, 68);

  y = 110;
  doc.setTextColor(20);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`${scan.fruit_name} — ${scan.freshness_category}`, 40, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Fruit confidence: ${scan.fruit_confidence.toFixed(1)}%   ·   Freshness confidence: ${scan.freshness_confidence.toFixed(1)}%`, 40, y);
  y += 20;

  const dataUrl = await imgToDataURL(scan.image_url);
  if (dataUrl) {
    try {
      doc.addImage(dataUrl, "JPEG", 40, y, 220, 220);
    } catch { /* ignore */ }
  }

  let ry = y;
  const rx = 290;
  const lh = 22;
  const drawRow = (label: string, value: number) => {
    doc.setFont("helvetica", "normal");
    doc.text(label, rx, ry);
    doc.setFont("helvetica", "bold");
    doc.text(`${value}/100`, W - 40, ry, { align: "right" });
    doc.setDrawColor(220);
    doc.line(rx, ry + 4, W - 40, ry + 4);
    ry += lh;
  };
  drawRow("Freshness score", scan.freshness_score);
  drawRow("Quality score", scan.quality_score);
  drawRow("Ripeness score", scan.ripeness_score);
  drawRow("Damage score", scan.damage_score);

  y = Math.max(y + 240, ry + 10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Recommendation", 40, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(doc.splitTextToSize(scan.recommendation || "—", W - 80), 40, y);
  y += 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Why did AI give this result?", 40, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const obs = (scan.observations as unknown as string[]) ?? [];
  for (const o of obs) {
    const lines = doc.splitTextToSize(`• ${o}`, W - 80);
    doc.text(lines, 40, y);
    y += lines.length * 12 + 4;
  }

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by FruitSense AI · Powered by Lovable Cloud", 40, doc.internal.pageSize.getHeight() - 24);

  doc.save(`fruitsense-${scan.id.slice(0, 8)}.pdf`);
}
